[package]
name = "Chapter-1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graph = "0.3.0"
halo2_proofs = "0.3.0"
plotters = "0.3.4"
rand_core = "0.6.4"
